version: '3.9'

services:
  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - user_net
    container_name: redis_container

  user-service:
    build:
      context: .
      dockerfile: apps/user-service/Dockerfile
    restart: on-failure
    env_file:
      - ./apps/user-service/.env
    depends_on:
      - redis
    ports:
      - '3000:3000'
    networks:
      - user_net
    environment:
      DATABASE_URL: 'postgresql://my_user:32oHINflGWcTNkQ3RS1m4kcv5X1HIMcS@dpg-d34lju95pdvs73e1vqsg-a.oregon-postgres.render.com/user-service'
      REDIS_HOST: redis
      REDIS_PORT: 6379
    container_name: user_service_container

volumes:
  redis_data:

networks:
  user_net:
    driver: bridge
